import { PrismaClient, PropertyType, TransactionType, PropertyCondition, PropertyStatus, Prisma } from '@prisma/client';

export async function seedProperties(prisma: PrismaClient, users: any) {
  console.log('\n📦 Seeding Properties...');

  const adminUser = users.admin;
  const agentUser = users.agent;

  const properties: Prisma.PropertyCreateInput[] = [
    {
      title: 'Villa Moderne avec Piscine',
      description: 'Magnifique villa moderne de 250m² avec piscine, jardin paysager et vue panoramique. Située dans un quartier calme et résidentiel, cette propriété offre 4 chambres spacieuses, 3 salles de bains, un grand salon-salle à manger, une cuisine équipée et un garage double.',
      propertyType: PropertyType.VILLA,
      transactionType: TransactionType.SALE,
      location: 'Ivandry',
      city: 'Antananarivo',
      address: '15 Rue des Jacarandas',
      zipCode: '101',
      price: 450000,
      pricePerM2: 1800,
      currency: 'EUR',
      totalSize: 250,
      livingSize: 220,
      landSize: 800,
      bedrooms: 4,
      bathrooms: 3,
      rooms: 8,
      floors: 2,
      yearBuilt: 2020,
      condition: PropertyCondition.EXCELLENT,
      features: ['Piscine', 'Jardin', 'Garage', 'Terrasse', 'Vue panoramique'],
      amenities: ['Climatisation', 'Chauffage', 'Cuisine équipée', 'Dressing', 'Buanderie'],
      images: [
        '/images/properties/villa1-1.jpg',
        '/images/properties/villa1-2.jpg',
        '/images/properties/villa1-3.jpg',
      ],
      coverImage: '/images/properties/villa1-1.jpg',
      status: PropertyStatus.AVAILABLE,
      isFeatured: true,
      isPublished: true,
      views: 245,
      reference: 'VIL-2024-001',
      energyClass: 'B',
      owner: adminUser ? { connect: { id: adminUser.id } } : undefined,
    },
    {
      title: 'Appartement Centre-Ville',
      description: 'Bel appartement de 85m² au cœur de la ville, proche de toutes commodités. 2 chambres, salon lumineux, cuisine moderne, balcon avec vue sur la ville.',
      propertyType: PropertyType.APARTMENT,
      transactionType: TransactionType.RENT,
      location: 'Analakely',
      city: 'Antananarivo',
      address: '42 Avenue de l\'Indépendance',
      zipCode: '101',
      price: 120000,
      rentPrice: 800,
      pricePerM2: 1412,
      currency: 'EUR',
      totalSize: 85,
      livingSize: 85,
      bedrooms: 2,
      bathrooms: 1,
      rooms: 4,
      floor: 3,
      floors: 1,
      yearBuilt: 2018,
      condition: PropertyCondition.GOOD,
      features: ['Balcon', 'Ascenseur', 'Interphone', 'Cave'],
      amenities: ['Climatisation', 'Cuisine équipée', 'Parking'],
      images: [
        '/images/properties/apt1-1.jpg',
        '/images/properties/apt1-2.jpg',
      ],
      coverImage: '/images/properties/apt1-1.jpg',
      status: PropertyStatus.AVAILABLE,
      isFeatured: true,
      isPublished: true,
      views: 189,
      reference: 'APT-2024-002',
      energyClass: 'C',
      charges: 150,
      owner: agentUser ? { connect: { id: agentUser.id } } : undefined,
    },
    {
      title: 'Terrain Constructible 1000m²',
      description: 'Superbe terrain constructible de 1000m² dans un quartier en développement. Viabilisé, plat, idéal pour construction villa ou immeuble. Proche écoles et commerces.',
      propertyType: PropertyType.TERRAIN_RESIDENTIAL,
      transactionType: TransactionType.SALE,
      location: 'Ambatobe',
      city: 'Antananarivo',
      address: 'Lot IVG 234',
      zipCode: '102',
      price: 80000,
      pricePerM2: 80,
      currency: 'EUR',
      totalSize: 1000,
      landSize: 1000,
      features: ['Viabilisé', 'Plat', 'Clôturé', 'Accès goudronné'],
      amenities: ['Eau', 'Électricité', 'Tout-à-l\'égout'],
      images: [
        '/images/properties/terrain1-1.jpg',
      ],
      coverImage: '/images/properties/terrain1-1.jpg',
      status: PropertyStatus.AVAILABLE,
      isFeatured: false,
      isPublished: true,
      views: 156,
      reference: 'TER-2024-003',
      owner: adminUser ? { connect: { id: adminUser.id } } : undefined,
    },
    {
      title: 'Maison Familiale 4 Chambres',
      description: 'Charmante maison familiale de 180m² avec jardin. 4 chambres, 2 salles de bains, grand salon, cuisine aménagée, garage. Quartier calme et sécurisé.',
      propertyType: PropertyType.HOUSE,
      transactionType: TransactionType.SALE,
      location: 'Ambohimanarina',
      city: 'Antananarivo',
      address: '28 Rue des Roses',
      zipCode: '101',
      price: 280000,
      pricePerM2: 1556,
      currency: 'EUR',
      totalSize: 180,
      livingSize: 160,
      landSize: 400,
      bedrooms: 4,
      bathrooms: 2,
      rooms: 7,
      floors: 1,
      yearBuilt: 2015,
      condition: PropertyCondition.GOOD,
      features: ['Jardin', 'Garage', 'Terrasse', 'Véranda'],
      amenities: ['Cuisine équipée', 'Cheminée', 'Buanderie'],
      images: [
        '/images/properties/house1-1.jpg',
        '/images/properties/house1-2.jpg',
      ],
      coverImage: '/images/properties/house1-1.jpg',
      status: PropertyStatus.AVAILABLE,
      isFeatured: false,
      isPublished: true,
      views: 98,
      reference: 'HOU-2024-004',
      energyClass: 'D',
      owner: agentUser ? { connect: { id: agentUser.id } } : undefined,
    },
    {
      title: 'Studio Meublé Centre',
      description: 'Studio meublé de 30m² idéal étudiant ou jeune actif. Cuisine équipée, salle d\'eau, proche transports et commerces.',
      propertyType: PropertyType.STUDIO,
      transactionType: TransactionType.RENT,
      location: 'Ankorondrano',
      city: 'Antananarivo',
      address: '12 Rue Rainibetsimisaraka',
      zipCode: '101',
      price: 45000,
      rentPrice: 350,
      pricePerM2: 1500,
      currency: 'EUR',
      totalSize: 30,
      livingSize: 30,
      bedrooms: 1,
      bathrooms: 1,
      rooms: 1,
      floor: 2,
      floors: 1,
      yearBuilt: 2019,
      condition: PropertyCondition.EXCELLENT,
      features: ['Meublé', 'Balcon', 'Ascenseur'],
      amenities: ['Cuisine équipée', 'Internet', 'Parking'],
      images: [
        '/images/properties/studio1-1.jpg',
      ],
      coverImage: '/images/properties/studio1-1.jpg',
      status: PropertyStatus.AVAILABLE,
      isFeatured: false,
      isPublished: true,
      views: 234,
      reference: 'STU-2024-005',
      energyClass: 'B',
      charges: 80,
      owner: adminUser ? { connect: { id: adminUser.id } } : undefined,
    },
    {
      title: 'Villa de Luxe Vue Mer',
      description: 'Exceptionnelle villa de luxe de 400m² avec vue imprenable sur la mer. 6 chambres en suite, piscine à débordement, spa, home cinéma, cuisine gastronomique. Prestations haut de gamme.',
      propertyType: PropertyType.VILLA,
      transactionType: TransactionType.SALE,
      location: 'Flic en Flac',
      city: 'Rivière Noire',
      address: 'Coastal Road',
      zipCode: '90000',
      price: 1200000,
      pricePerM2: 3000,
      currency: 'EUR',
      totalSize: 400,
      livingSize: 350,
      landSize: 1500,
      bedrooms: 6,
      bathrooms: 6,
      rooms: 12,
      floors: 2,
      yearBuilt: 2022,
      condition: PropertyCondition.NEW,
      features: ['Piscine à débordement', 'Spa', 'Home cinéma', 'Cave à vin', 'Garage 3 voitures', 'Vue mer'],
      amenities: ['Climatisation', 'Domotique', 'Cuisine gastronomique', 'Dressing', 'Buanderie', 'Salle de sport'],
      images: [
        '/images/properties/villa2-1.jpg',
        '/images/properties/villa2-2.jpg',
        '/images/properties/villa2-3.jpg',
        '/images/properties/villa2-4.jpg',
      ],
      coverImage: '/images/properties/villa2-1.jpg',
      status: PropertyStatus.AVAILABLE,
      isFeatured: true,
      isPublished: true,
      views: 567,
      reference: 'VIL-2024-006',
      energyClass: 'A',
      owner: adminUser ? { connect: { id: adminUser.id } } : undefined,
    },
    {
      title: 'Local Commercial Centre-Ville',
      description: 'Local commercial de 120m² en plein centre-ville, idéal pour boutique ou bureau. Grande vitrine, arrière-boutique, sanitaires.',
      propertyType: PropertyType.SHOP,
      transactionType: TransactionType.RENT,
      location: 'Analakely',
      city: 'Antananarivo',
      address: '78 Avenue de l\'Indépendance',
      zipCode: '101',
      price: 180000,
      rentPrice: 1500,
      pricePerM2: 1500,
      currency: 'EUR',
      totalSize: 120,
      livingSize: 120,
      floors: 1,
      yearBuilt: 2010,
      condition: PropertyCondition.GOOD,
      features: ['Grande vitrine', 'Arrière-boutique', 'Sanitaires', 'Climatisation'],
      amenities: ['Alarme', 'Volets roulants'],
      images: [
        '/images/properties/shop1-1.jpg',
      ],
      coverImage: '/images/properties/shop1-1.jpg',
      status: PropertyStatus.AVAILABLE,
      isFeatured: false,
      isPublished: true,
      views: 145,
      reference: 'COM-2024-007',
      charges: 200,
      owner: agentUser ? { connect: { id: agentUser.id } } : undefined,
    },
    {
      title: 'Penthouse Luxe 200m²',
      description: 'Somptueux penthouse de 200m² au dernier étage avec terrasse de 80m². Vue à 360° sur la ville. 3 chambres, 3 salles de bains, salon cathédrale, cuisine ouverte haut de gamme.',
      propertyType: PropertyType.PENTHOUSE,
      transactionType: TransactionType.SALE,
      location: 'Ivandry',
      city: 'Antananarivo',
      address: 'Résidence Prestige, Avenue de France',
      zipCode: '101',
      price: 650000,
      pricePerM2: 3250,
      currency: 'EUR',
      totalSize: 200,
      livingSize: 200,
      bedrooms: 3,
      bathrooms: 3,
      rooms: 6,
      floor: 8,
      floors: 1,
      yearBuilt: 2021,
      condition: PropertyCondition.NEW,
      features: ['Terrasse 80m²', 'Vue panoramique', 'Ascenseur privatif', 'Jacuzzi'],
      amenities: ['Climatisation', 'Domotique', 'Cuisine haut de gamme', 'Dressing', 'Cave', 'Parking 2 places'],
      images: [
        '/images/properties/penthouse1-1.jpg',
        '/images/properties/penthouse1-2.jpg',
        '/images/properties/penthouse1-3.jpg',
      ],
      coverImage: '/images/properties/penthouse1-1.jpg',
      status: PropertyStatus.AVAILABLE,
      isFeatured: true,
      isPublished: true,
      views: 423,
      reference: 'PEN-2024-008',
      energyClass: 'A',
      charges: 300,
      owner: adminUser ? { connect: { id: adminUser.id } } : undefined,
    },
  ];

  for (const property of properties) {
    await prisma.property.create({
      data: property,
    });
  }

  console.log(`✅ ${properties.length} propriétés créées avec succès`);
}
